INFL-0000-release-fix (#6)

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -42,11 +42,6 @@ jobs:
           token: ${{ steps.app_token.outputs.token }}
           fetch-depth: 0
 
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
       - name: Set up Helm
         uses: azure/setup-helm@v4
         with:
@@ -103,11 +98,19 @@ jobs:
           VERSION_NO_V=${NEW_VERSION#v}
           sed -i "s/^version:.*/version: ${VERSION_NO_V}/" ci-runner-worker/Chart.yaml
           sed -i "s/^appVersion:.*/appVersion: \"${VERSION_NO_V}\"/" ci-runner-worker/Chart.yaml
-          git config user.name "github-actions[bot]"
+
+      - name: Commit and push Chart.yaml (bypass protection)
+        run: |
+          # git identity
           git config user.email "github-actions[bot]@users.noreply.github.com"
+          git config user.name "github-actions[bot]"
+          
+          # commit (don't fail the job if there is nothing to commit)
           git add ci-runner-worker/Chart.yaml
-          git commit -m "chore: bump chart version to ${NEW_VERSION}" || echo "No changes to commit"
-          git push
+          git commit -m "chore: bump chart version to ${{ steps.version.outputs.new_version }}" || exit 0
+
+          # push branch (bypass protection)
+          git push origin HEAD:main
 
       - name: Package Helm chart
         run: |
